# Generated by Django 5.1.7 on 2025-06-20 10:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=models.ImageField(upload_to=accounts.models.user_directory_path),
        ),
    ]
