server {
    listen 80;

    location / {
        root   D:/elo05/frontend/build;
        index index.html index.htm;
        try_files $uri /index.html;
    }

    # Serve static JS/CSS files
        location /static/ {
            alias D:/elo05/frontend/build/static/;
        }

    location /api/ {
        proxy_pass http://192.168.1.80:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    
}
