# Generated by Django 5.1.7 on 2025-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowbit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cavity_count',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
