# Generated by Django 5.1.7 on 2025-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
