# Generated by Django 5.1.7 on 2025-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='flowbit_uploaded_documents/%Y/%m/%d/'),
        ),
    ]
